---
- name: "Group - AWS - Create {{ item_group.name }}"
  iam_group:
    name: "{{ item_group.name }}"
    state: present
    managed_policy: "{{ item_group.aws_managed_policies }}"
  register: aws_group
