---
- name: Group | Unix | Create {{ item_group.name }}
  ansible.builtin.group:
    name: "{{ item_group.name }}"
    state: present

- name: Group | Unix | Check sudoers
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ item_sudoers.regex }}"
    line: "{{ item_sudoers.value }}"
  when: item_group.unix_sudoers_line is defined
  with_items: "{{ item_group.unix_sudoers_line }}"
  loop_control:
    loop_var: item_sudoers
