---
# Config roles
- name: Configure roles
  ansible.builtin.include_tasks: role.yml
  with_items: "{{ iam_roles }}"
  when: iam_roles is defined
  loop_control:
    loop_var: item_role

# Config groups
- name: Configure groups
  ansible.builtin.include_tasks: group.yml
  with_items: "{{ iam_groups }}"
  when: iam_groups is defined
  loop_control:
    loop_var: item_group

# Config users
- name: Configure users
  ansible.builtin.include_tasks: user.yml
  with_items: "{{ iam_users }}"
  when: iam_groups is defined
  loop_control:
    loop_var: item_user
