---
- name: "User - LINUX - Create/Delete {{ item_user.name }}"
  user:
    name: "{{ item_user.name }}"
    state: "{{ item_user.state |d('present') }}"
    comment: "{{ item_user.full_name |d(omit) }}"
    group: "{{ item_user.group |d(omit) }}"
    groups: "{{ item_user.groups |d(omit) }}"
    home: "{{ item_user.home |d(omit) }}"
    shell: "{{ item_user.shell |d(omit) }}"

- name: User - LINUX - Define SSH Authorized key
  authorized_key:
    user: "{{ item_user.name }}"
    state: present
    key: "{{ item_user.ssh_pub_key |d('ansible_pub_key_not_found') }}"
  when: not ansible_check_mode